version: '3'

services:
  webcrawler.spider.web:
    image: webcrawler.spider.web
    build:
      context: ./src/WebCrawler.Spider.Web
      dockerfile: Dockerfile
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: